package agent

import (
	"fmt"
	"os"
	"sort"

	"go.yaml.in/yaml/v3"
)

// =============================================================================
// docker-compose override generation for cross-workload DNS
// =============================================================================
//
// Each Jetty workload runs in its own docker-compose project on its own
// bridge network. Containers in different projects can't see each other in
// Docker's embedded DNS, and don't share /etc/hosts with the host. So
// without help, a container in workload "nginx" can't resolve "wordpress"
// even though both are valid workload names with stable mesh IPs.
//
// We fix that by writing a docker-compose.override.yml alongside the
// user's docker-compose.yml at deploy time. The override populates each
// service's extra_hosts with every workload-name -> mesh-IP mapping in
// the cluster. Compose merges base and override at runtime, so each
// container ends up with /etc/hosts entries for every workload.
//
// Why an override file rather than mutating the user's compose:
//   - User's source stays untouched.
//   - Compose handles the merge (no edge cases with anchors, env vars).
//   - We can regenerate without re-parsing the user's file.
//
// Limitations:
//   - The override is written at deploy time. When a NEW workload is added
//     to the cluster, existing workloads' override files don't refresh
//     automatically - we rewrite them in place but containers see the new
//     entries only after restart. Stable IPs for existing workloads mean
//     failover doesn't need any of this; only new-workload discovery does.
//   - We touch only top-level `services`. Compose extension services
//     (anchors, x-* keys) are passed through unchanged.

// composeRoot models the bits of compose v3 we need - just the services map.
type composeRoot struct {
	Services map[string]yaml.Node `yaml:"services"`
}

// parseComposeServiceNames returns the names of every service defined in a
// compose YAML document. Order is sorted for deterministic output.
//
// The full compose spec is sprawling; we only care about the top-level
// services map. yaml.v3 lets us keep everything else as raw nodes so we
// don't have to model the rest of the spec.
func parseComposeServiceNames(composeYAML []byte) ([]string, error) {
	var root composeRoot
	if err := yaml.Unmarshal(composeYAML, &root); err != nil {
		return nil, fmt.Errorf("parse compose yaml: %w", err)
	}
	if len(root.Services) == 0 {
		return nil, nil
	}
	names := make([]string, 0, len(root.Services))
	for name := range root.Services {
		names = append(names, name)
	}
	sort.Strings(names)
	return names, nil
}

// buildHostsOverride generates a compose override document that adds
// extra_hosts to every named service. Returns the YAML bytes, ready to
// write to docker-compose.override.yml.
//
// Format produced (one entry per workload, sorted by hostname):
//
//	services:
//	  web:
//	    extra_hosts:
//	      - "nginx:10.100.0.20"
//	      - "postgres:10.100.0.51"
//	      - "wordpress:10.100.0.50"
//	  worker:
//	    extra_hosts:
//	      - ...
//
// Returns an empty document if there are no services or no hosts to add.
func buildHostsOverride(serviceNames []string, hosts map[string]string) ([]byte, error) {
	if len(serviceNames) == 0 || len(hosts) == 0 {
		// Empty override - still a valid compose file, contributes nothing.
		return []byte("# Generated by Jetty - no extra_hosts to inject\nservices: {}\n"), nil
	}

	// Sorted name list for deterministic output (so the file hash is stable
	// and compose's "config changed?" detection only fires on real changes).
	hostNames := make([]string, 0, len(hosts))
	for name := range hosts {
		hostNames = append(hostNames, name)
	}
	sort.Strings(hostNames)

	hostEntries := make([]string, 0, len(hostNames))
	for _, name := range hostNames {
		hostEntries = append(hostEntries, fmt.Sprintf("%s:%s", name, hosts[name]))
	}

	// Build a yaml.Node tree by hand so we control formatting precisely.
	doc := &yaml.Node{Kind: yaml.DocumentNode}
	root := &yaml.Node{Kind: yaml.MappingNode}
	doc.Content = []*yaml.Node{root}

	// services:
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "services"},
	)
	servicesNode := &yaml.Node{Kind: yaml.MappingNode}
	root.Content = append(root.Content, servicesNode)

	for _, svcName := range serviceNames {
		// <svcName>:
		servicesNode.Content = append(servicesNode.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: svcName},
		)
		// { extra_hosts: [...] }
		svcMap := &yaml.Node{Kind: yaml.MappingNode}
		svcMap.Content = append(svcMap.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "extra_hosts"},
		)
		hostsList := &yaml.Node{Kind: yaml.SequenceNode}
		for _, e := range hostEntries {
			hostsList.Content = append(hostsList.Content,
				&yaml.Node{Kind: yaml.ScalarNode, Style: yaml.DoubleQuotedStyle, Value: e},
			)
		}
		svcMap.Content = append(svcMap.Content, hostsList)
		servicesNode.Content = append(servicesNode.Content, svcMap)
	}

	return yaml.Marshal(doc)
}

// writeHostsOverride writes the override YAML to overridePath. Returns the
// generated bytes (in case the caller wants to hash them) and any error.
//
// File mode 0644 matches the user's docker-compose.yml on the same path.
func writeHostsOverride(overridePath string, serviceNames []string, hosts map[string]string) ([]byte, error) {
	data, err := buildHostsOverride(serviceNames, hosts)
	if err != nil {
		return nil, fmt.Errorf("build override: %w", err)
	}
	if err := os.WriteFile(overridePath, data, 0644); err != nil {
		return nil, fmt.Errorf("write override: %w", err)
	}
	return data, nil
}

// currentWorkloadHosts builds a workload-name -> mesh-IP map from the
// agent's current state. Caller must hold a.stateMu (read or write).
func (a *Agent) currentWorkloadHosts() map[string]string {
	hosts := make(map[string]string, len(a.state.Workloads))
	for _, wl := range a.state.Workloads {
		if wl.Name != "" && wl.IP != "" {
			hosts[wl.Name] = wl.IP
		}
	}
	return hosts
}
