package agent

import (
	"net"
	"net/http"
	"os/exec"
	"sync"
	"time"

	"github.com/gorilla/websocket"
	"github.com/hashicorp/memberlist"
	"github.com/songgao/water"
)

// =============================================================================
// Constants
// =============================================================================

const (
	// Timing constants. The defaults below are tuned for "seamless-ish"
	// failover: typical detection sub-second via memberlist + 5s polling
	// fallback, plus a 5s failover loop. Total time-to-claim on node death
	// is usually under 10 seconds. The HealthTimeout is the hard backstop
	// when memberlist is unavailable and we're relying on HTTP gossip.
	HealthTimeout         = 15 * time.Second // Hard timeout for HTTP-gossip mode (memberlist usually fires sub-second)
	GossipInterval        = 5 * time.Second  // How often to check peers and sync state in HTTP-gossip fallback mode
	FailoverCheckInterval = 5 * time.Second  // How often to scan for orphaned workloads
	FailoverGracePeriod   = 30 * time.Second // Peer must stay unreachable this long before failover claims its workloads
	FailoverStartupGrace  = 90 * time.Second // No failover claims for the first N seconds after agent startup - lets memberlist + checkPeers converge so we don't claim based on stale peer-health from before our last shutdown
	IPMonitorInterval     = 10 * time.Second // How often to check for WARP IP changes
	CPUSampleInterval     = 30 * time.Second // How often to sample CPU usage
	TombstoneMaxAge       = 1 * time.Hour    // How long to keep deletion tombstones

	// Timeouts
	DefaultHTTPTimeout   = 30 * time.Second
	PeerHTTPTimeout      = 5 * time.Second
	UnhealthyPeerTimeout = 1 * time.Second
	QuickHTTPTimeout     = 3 * time.Second

	// Network
	DefaultAPIPort     = 6880
	DefaultServiceCIDR = "10.100.0.0/16"

	// Cloudflared retry settings
	CloudflaredInitialBackoff = 5 * time.Second
	CloudflaredMaxBackoff     = 2 * time.Minute
	CloudflaredMaxFailures    = 10
	CloudflaredSuccessReset   = 30 * time.Second
)

// =============================================================================
// HTTP Clients
// =============================================================================

// Global HTTP clients with different timeouts for different use cases.
// All share a transport with a short IdleConnTimeout: after a network
// event (laptop suspend/resume, WARP reconnect) the kernel can hold an
// idle connection in the pool that's silently dead. The next request
// hangs against it for the full client Timeout. Forcing the pool to
// recycle every few seconds means a stale connection costs at most one
// round of waiting before a fresh dial happens.
func newClusterTransport() *http.Transport {
	t := http.DefaultTransport.(*http.Transport).Clone()
	t.IdleConnTimeout = 5 * time.Second
	t.MaxIdleConnsPerHost = 4
	return t
}

var (
	httpClient          = &http.Client{Timeout: DefaultHTTPTimeout, Transport: newClusterTransport()}   // General requests (30s)
	peerClient          = &http.Client{Timeout: PeerHTTPTimeout, Transport: newClusterTransport()}      // Peer communication (5s)
	unhealthyPeerClient = &http.Client{Timeout: UnhealthyPeerTimeout, Transport: newClusterTransport()} // Known-unhealthy peers (1s)
)

// =============================================================================
// Core Types
// =============================================================================

// Peer represents a node in the cluster
type Peer struct {
	ID       string    `json:"id"`   // HWID (hardware ID)
	Name     string    `json:"name"` // Hostname
	IP       string    `json:"ip"`   // WARP IP (100.96.x.x) - primary address for node communication
	Healthy  bool      `json:"healthy"`
	LastSeen time.Time `json:"last_seen"`
	Version  string    `json:"version"` // Agent version
	Arch     string    `json:"arch"`    // CPU architecture (amd64, arm64, etc.)
	// APIKey is this peer's inbound credential. Other peers present
	// this value in X-API-Key when calling endpoints that require auth.
	// Generated by the peer itself at first bootstrap and registered
	// with the cluster during /api/join.
	//
	// json:"-" so it never accidentally serializes through endpoints
	// that return Peer objects (status, list-nodes, sync). The key is
	// propagated explicitly via:
	//   - the /api/join response (peerWire wire type)
	//   - memberlist NodeMeta.APIKey
	// and never via the default Peer marshal.
	APIKey string `json:"-"`
}

// Workload represents a Docker Compose application
type Workload struct {
	Name         string   `json:"name"`                    // DNS hostname
	IP           string   `json:"ip"`                      // Service IP (routed via WARP)
	Compose      string   `json:"compose"`                 // Default compose (used if no arch-specific)
	ComposeAmd64 string   `json:"compose_amd64,omitempty"` // Optional: amd64-specific compose
	ComposeArm64 string   `json:"compose_arm64,omitempty"` // Optional: arm64-specific compose
	Revive       bool     `json:"revive"`                  // Auto-failover to another node if owner dies
	Autostart    bool     `json:"autostart"`               // Auto-start when Jetty starts up
	AllowedNodes []string `json:"allowed_nodes,omitempty"` // Node whitelist: empty/["*"] = all, otherwise node names/IDs
	// Tags group workloads for filtering and bulk operations (start
	// all tagged "media", export all tagged "prod", etc.). Free-form
	// strings; validated with validTagPattern. Sorted+deduped on
	// ingest so the wire form is canonical.
	Tags []string `json:"tags,omitempty"`
	// RegistryAuth optionally authenticates this workload's image pull
	// against a private registry. The token itself is never stored here -
	// TokenRef names a key in the encrypted env store whose value is the
	// registry password/PAT. When nil, pulls run with no Jetty-managed
	// credentials (public images, or whatever the host docker config
	// already provides) - identical to pre-feature behavior.
	RegistryAuth *RegistryAuth `json:"registry_auth,omitempty"`
	Owner        string        `json:"owner"`   // Node HWID
	Version      int64         `json:"version"` // Unix timestamp
}

// RegistryAuth tells Jetty how to authenticate an image pull for a workload.
// The secret value lives in the encrypted, cluster-synced env store; this
// struct only carries a *reference* to it (TokenRef) so the workload record
// itself - which syncs across the cluster and renders in the dashboard in
// the clear - never contains a credential.
type RegistryAuth struct {
	Registry string `json:"registry"`           // Registry host, e.g. "ghcr.io"
	Username string `json:"username,omitempty"` // Registry username; defaults to "x-access-token" for PATs
	TokenRef string `json:"token_ref"`          // Env-store key holding the token/PAT
}

// DeletedWorkload represents a tombstone for a deleted workload to propagate deletions
type DeletedWorkload struct {
	IP      string `json:"ip"`      // The IP of the deleted workload
	Version int64  `json:"version"` // Timestamp when deleted (must be > workload version to take effect)
}

// DeletedEnvKey represents a tombstone for a deleted environment variable to propagate deletions
type DeletedEnvKey struct {
	Key     string `json:"key"`     // The name of the deleted env key
	Version int64  `json:"version"` // Timestamp when deleted
}

// State represents the cluster-wide state
type State struct {
	Peers            map[string]*Peer            `json:"peers"`                       // ID -> Peer
	Workloads        map[string]*Workload        `json:"workloads"`                   // IP -> Workload
	DeletedWorkloads map[string]*DeletedWorkload `json:"deleted_workloads,omitempty"` // IP -> tombstone (for sync propagation)
	CFToken          string                      `json:"cf_token,omitempty"`          // Cloudflare tunnel token (shared cluster-wide)
	WarpToken        string                      `json:"warp_token,omitempty"`        // Cloudflare WARP connector token (shared cluster-wide)
	EnvData          map[string]string           `json:"env_data,omitempty"`          // Encrypted environment variables (key -> encrypted value)
	DeletedEnvKeys   map[string]*DeletedEnvKey   `json:"deleted_env_keys,omitempty"`  // Key -> tombstone (for sync propagation)

	// AdminKey is the cluster-wide operator/dashboard credential.
	// Bootstrapped from JETTY_SECRET on the first node, persisted, and
	// propagated to joiners via /api/join. Set on every node so the
	// dashboard works regardless of which node the operator hits.
	AdminKey string `json:"admin_key,omitempty"`

	// EncryptionKey is the raw 32-byte AES key used to encrypt env_data.
	// Generated on first bootstrap, persisted, propagated to joiners via
	// /api/join. Replaces the older Argon2id(secret, salt) derivation.
	EncryptionKey []byte `json:"encryption_key,omitempty"`

	// SelfAPIKey is THIS node's outbound peer credential. It's also the
	// value stored in our own Peers entry on every other node. Never
	// shared via /api/sync; only released to peers during /api/join.
	SelfAPIKey string `json:"self_api_key,omitempty"`

	// JoinTokens is the set of pending one-time join tokens. Generated
	// by an admin via POST /api/tokens, consumed exactly once by a
	// joining node. Burned tokens are kept around for a short audit
	// window then garbage-collected.
	JoinTokens map[string]*JoinToken `json:"join_tokens,omitempty"`

	// BackupSchedule is the cluster-wide scheduled-backup config.
	// Persisted so a restart preserves the schedule. nil means
	// scheduled backups are disabled.
	BackupSchedule *BackupSchedule `json:"backup_schedule,omitempty"`

	// EncryptionSalt is the legacy Argon2id salt. Kept on disk so an
	// upgrade can read pre-existing env_data with the old key once,
	// re-encrypt it under EncryptionKey, then ignore this field.
	EncryptionSalt []byte `json:"encryption_salt,omitempty"`
}

// BackupSchedule controls the agent's automatic-backup loop.
// Configured via POST /api/backup/schedule (admin-only); persisted in
// state and gossiped so any node can run the backup. Only the
// least-HWID healthy node actually writes the file - same election
// rule failover uses, so we don't get N copies on every node.
type BackupSchedule struct {
	IntervalMinutes int       `json:"interval_minutes"`        // 0 = disabled
	Retention       int       `json:"retention,omitempty"`     // keep this many on-disk backups (0 = unlimited)
	Passphrase      string    `json:"passphrase,omitempty"`    // optional - if set, every scheduled backup is JETTY-ENC-V1 wrapped
	LastRunAt       time.Time `json:"last_run_at,omitempty"`   // updated on every successful run
	LastStatus      string    `json:"last_status,omitempty"`   // "ok" or "error: ..."
	LastBackupPath  string    `json:"last_backup_path,omitempty"`
	UpdatedAt       time.Time `json:"updated_at,omitempty"`    // when the schedule itself was last changed
}

// JoinToken is a single-use bearer credential that authorizes a new
// node to call POST /api/join exactly once. Generated by an
// admin-authenticated request to POST /api/tokens; the token's ID *is*
// its secret (random 32 bytes hex), so a stolen JoinTokens map gives an
// attacker every unburned token. Burning sets Used=true and is
// idempotent - replays after the first successful join are rejected.
type JoinToken struct {
	ID        string    `json:"id"`                    // Random hex; the token value itself
	CreatedAt time.Time `json:"created_at"`            // When minted
	ExpiresAt time.Time `json:"expires_at"`            // After this, refused even if unused
	Note      string    `json:"note,omitempty"`        // Free-form ("for arnold's laptop")
	Used      bool      `json:"used"`                  // True after a successful join consumed it
	UsedBy    string    `json:"used_by,omitempty"`     // Joining peer's ID (audit)
	UsedAt    time.Time `json:"used_at,omitempty"`     // When consumed
}

// NewState creates an empty state with initialized maps
func NewState() *State {
	return &State{
		Peers:            make(map[string]*Peer),
		Workloads:        make(map[string]*Workload),
		DeletedWorkloads: make(map[string]*DeletedWorkload),
		EnvData:          make(map[string]string),
		DeletedEnvKeys:   make(map[string]*DeletedEnvKey),
		JoinTokens:       make(map[string]*JoinToken),
	}
}

// =============================================================================
// TCP Proxy Types (for userspace tunneling)
// =============================================================================

// tunnelConn wraps a WebSocket connection with a write mutex to prevent
// concurrent writes which would cause a panic in gorilla/websocket.
type tunnelConn struct {
	conn    *websocket.Conn
	writeMu sync.Mutex
}

// WriteMessage sends a message through the WebSocket with proper synchronization.
func (tc *tunnelConn) WriteMessage(messageType int, data []byte) error {
	tc.writeMu.Lock()
	defer tc.writeMu.Unlock()
	return tc.conn.WriteMessage(messageType, data)
}

// tcpProxyConn represents an active TCP proxy connection through the tunnel.
type tcpProxyConn struct {
	conn      net.Conn    // TCP connection to the workload (nil while pending)
	wsConn    *tunnelConn // WebSocket connection back to the tunnel peer (with write mutex)
	srcIP     net.IP          // Original source IP
	srcPort   uint16          // Original source port
	dstIP     net.IP          // Destination IP (workload)
	dstPort   uint16          // Destination port
	localSeq  uint32          // Our sequence number for responses
	remoteSeq uint32          // Remote sequence number (from client)
	mu        sync.Mutex      // Protects sequence numbers and conn
	ready     chan struct{}   // Closed when connection is established (nil = already ready)
	failed    bool            // True if connection establishment failed
}

// =============================================================================
// Agent Type
// =============================================================================

// Agent is the main Jetty agent that manages the cluster node
type Agent struct {
	// Identity
	hwid     string
	hostname string
	ip       string // WARP IP (100.96.x.x) - primary node address

	// Cloudflare
	cfTunnelID string // WARP connector tunnel ID (for workload route management)

	// Config
	dataDir       string
	apiPort       int
	serviceCIDR   string // CIDR for workload service IPs (routed via WARP)
	joinURL       string
	joinToken     string // JETTY_JOIN_TOKEN - required to call /api/join (consumed exactly once)
	clusterSecret string // JETTY_SECRET - bootstraps state.AdminKey on the first node; otherwise unused
	tunnelDomain  string // Cloudflare tunnel domain for API access
	tunnelHost    string // This node's specific tunnel hostname (e.g., "node1.cluster.example.com")

	// hostShellEnabled gates the WS /api/host/shell endpoint. Off by
	// default; set JETTY_HOST_SHELL=true to opt in. The endpoint hands
	// out an interactive shell as the agent runs (typically root with
	// privileged caps), so enabling it means anyone with JETTY_SECRET
	// has full host access on every node.
	hostShellEnabled bool

	// State
	state   *State
	stateMu sync.RWMutex
	// saveMu serializes saveState's write+rename. Without it,
	// concurrent goroutines call os.WriteFile on the same temp path
	// and their writes interleave at the kernel level, producing a
	// corrupted state.json.tmp that may then be renamed into place.
	saveMu sync.Mutex

	// Paths
	composeDir string
	hostsFile  string

	// Cloudflare tunnel
	cfCmd    *exec.Cmd
	cfMu     sync.Mutex
	cfStopCh chan struct{}

	// Runtime
	startTime           time.Time // When Jetty started (for uptime tracking)
	lastHeartbeatErrLog time.Time // Last time we logged a heartbeat error (to reduce spam)
	publicIP            string    // Cached public IP (set at startup to avoid slow lookups)
	cachedCPUPercent    float64   // Cached CPU usage (updated by background goroutine)
	cachedCPUMu         sync.RWMutex
	warpPreexisting     bool // Was a CloudflareWARP interface already present when we started? If so, don't tear it down on Stop().

	// Route management
	workloadRoutes   map[string]string // workload IP -> owner WARP IP (for remote workloads)
	workloadRoutesMu sync.Mutex

	// Container autoheal: last time we restarted each running-but-unhealthy
	// container, so a container that keeps coming up unhealthy isn't
	// restart-looped faster than healContainerCooldown.
	healTimes   map[string]time.Time
	healTimesMu sync.Mutex

	// Tunnel support for cross-node routing
	tunnelMode        string          // "ipip", "gre", or "" (none available)
	ipipWarnedPeers   map[string]bool // Peers we've already warned about tunnel failure
	ipipWarnedPeersMu sync.Mutex

	// Userspace tunnel (fallback when kernel IPIP/GRE not available)
	tunDevice    *water.Interface // TUN device for capturing workload traffic
	tunPeerConns sync.Map         // peerID -> *websocket.Conn (outgoing connections to peers)
	tunPeerIPs   sync.Map         // peerID -> string (peer WARP IP for tunnel)
	tunConnMu    sync.Mutex       // Protects WebSocket connection establishment
	tunTCPConns  sync.Map         // flowKey -> *tcpProxyConn (active TCP proxy connections)

	// Memberlist (cluster membership and failure detection)
	memberlist *memberlist.Memberlist
	mlDelegate *jettyDelegate

	// Failover tracking (prevents duplicate claims during deployment)
	failoverInProgress   map[string]time.Time // workload IP -> claim start time
	failoverInProgressMu sync.Mutex

	// peerUnhealthySince records when each peer first appeared
	// unreachable; used to debounce failover so a brief network blip
	// (laptop suspend/resume, WiFi handoff) doesn't trigger an
	// ownership claim. Cleared the moment the peer recovers.
	peerUnhealthySince   map[string]time.Time
	peerUnhealthySinceMu sync.Mutex

	// workloadMoveLocks serializes apiMoveWorkload calls for a given
	// workload name. Without this, double-clicking the dashboard's
	// Move button enqueues multiple POSTs that race each other -
	// move N+1 reads stale state, fires its DELETE against the *new*
	// owner, and silently destroys the workload it was supposed to
	// duplicate-move. One lock per name; entries are kept rather
	// than torn down because workload names are bounded and reusing
	// the same lock across moves of the same name is correct.
	workloadMoveLocks   map[string]*sync.Mutex
	workloadMoveLocksMu sync.Mutex

	// hostsBlockHash is the SHA-256 of the JETTY-managed block we last wrote
	// to /etc/hosts. updateHosts skips the write when the block hasn't changed,
	// which silences the per-gossip-tick churn on /etc/hosts.
	//
	// hostsMu serializes updateHosts callers. The function only takes
	// stateMu.RLock (shared), so without this, concurrent callers (e.g.
	// per-workload bulk-action goroutines) race on hostsBlockHash and can
	// interleave the read-modify-write of /etc/hosts itself.
	hostsMu        sync.Mutex
	hostsBlockHash [32]byte

	// maroonedLogged tracks when we last warned about a marooned workload
	// (no compatible node available - e.g. arm64-only workload but only
	// amd64 nodes left). Rate-limited to avoid log spam.
	maroonedLogged   map[string]time.Time
	maroonedLoggedMu sync.Mutex

	// hostsOverrideHash is a hash of the workload-name -> mesh-IP map
	// last reflected in our owned workloads' compose override files. When
	// the map changes we rewrite the override files so future workload
	// restarts pick up new entries.
	hostsOverrideHash [32]byte

	stopCh chan struct{}
}

// =============================================================================
// Sync Response Types
// =============================================================================

// peerWire is the on-the-wire representation of a Peer for the
// /api/join response. It mirrors Peer but EXPLICITLY includes APIKey
// (which Peer's json:"-" tag suppresses everywhere else) so the joiner
// can populate its peer table with the credentials needed to call each
// peer back. Used nowhere else.
type peerWire struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	IP       string    `json:"ip"`
	Healthy  bool      `json:"healthy"`
	LastSeen time.Time `json:"last_seen"`
	Version  string    `json:"version"`
	Arch     string    `json:"arch"`
	APIKey   string    `json:"api_key,omitempty"`
}

func peerToWire(p *Peer) peerWire {
	return peerWire{
		ID: p.ID, Name: p.Name, IP: p.IP, Healthy: p.Healthy,
		LastSeen: p.LastSeen, Version: p.Version, Arch: p.Arch, APIKey: p.APIKey,
	}
}

func (w peerWire) toPeer() *Peer {
	return &Peer{
		ID: w.ID, Name: w.Name, IP: w.IP, Healthy: w.Healthy,
		LastSeen: w.LastSeen, Version: w.Version, Arch: w.Arch, APIKey: w.APIKey,
	}
}

// SyncResponse represents the response from a /api/sync call
type SyncResponse struct {
	Workloads        []*Workload        `json:"workloads"`
	DeletedWorkloads []*DeletedWorkload `json:"deleted_workloads,omitempty"`
	EnvData          map[string]string  `json:"env_data,omitempty"`
	DeletedEnvKeys   []*DeletedEnvKey   `json:"deleted_env_keys,omitempty"`
}
