// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Jetty Support",
            "url": "https://github.com/ncwardell/jetty"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns health status of this node",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/agent.HealthResponse"
                        }
                    }
                }
            }
        },
        "/join": {
            "post": {
                "description": "Allows a new node to join the cluster using a token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Join cluster",
                "parameters": [
                    {
                        "description": "Join request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/agent.JoinRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/agent.JoinResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid token or secret",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Mesh IP collision",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Returns full cluster status including node info, peers, workloads, and connectivity status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Get cluster status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/agent.StatusResponse"
                        }
                    }
                }
            }
        },
        "/token": {
            "post": {
                "description": "Generates a new single-use token for joining the cluster (expires in 24h)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cluster"
                ],
                "summary": "Create join token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/agent.TokenResponse"
                        }
                    }
                }
            }
        },
        "/tunnel": {
            "get": {
                "description": "Returns Cloudflare tunnel configuration status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tunnel"
                ],
                "summary": "Get tunnel status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/agent.TunnelStatus"
                        }
                    }
                }
            },
            "post": {
                "description": "Sets the Cloudflare tunnel token (propagates to all nodes)",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "tunnel"
                ],
                "summary": "Configure tunnel",
                "parameters": [
                    {
                        "description": "Tunnel token",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/agent.TunnelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tunnel configured"
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes the Cloudflare tunnel configuration",
                "tags": [
                    "tunnel"
                ],
                "summary": "Remove tunnel",
                "responses": {
                    "204": {
                        "description": "Tunnel removed"
                    }
                }
            }
        },
        "/workloads": {
            "get": {
                "description": "Returns all workloads in the cluster",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workloads"
                ],
                "summary": "List all workloads",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/agent.Workload"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates and deploys a new Docker Compose workload with a mesh IP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workloads"
                ],
                "summary": "Deploy a new workload",
                "parameters": [
                    {
                        "description": "Workload configuration",
                        "name": "workload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/agent.WorkloadRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/agent.Workload"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Mesh IP already in use",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Deployment failed",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workloads/{name}": {
            "get": {
                "description": "Returns details for a specific workload by name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workloads"
                ],
                "summary": "Get workload details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workload name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/agent.Workload"
                        }
                    },
                    "404": {
                        "description": "Workload not found",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Stops and removes a workload from the cluster",
                "tags": [
                    "workloads"
                ],
                "summary": "Delete a workload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workload name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Workload deleted"
                    },
                    "404": {
                        "description": "Workload not found",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workloads/{name}/logs": {
            "get": {
                "description": "Returns container logs for a workload",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "workloads"
                ],
                "summary": "Get workload logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workload name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Container logs",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Workload not found",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workloads/{name}/move": {
            "post": {
                "description": "Migrates a workload to a different node in the cluster",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "workloads"
                ],
                "summary": "Move workload to another node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workload name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Target node",
                        "name": "target",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/agent.MoveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Workload moved"
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Workload or target not found",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workloads/{name}/start": {
            "post": {
                "description": "Starts the containers for a workload that was previously stopped",
                "tags": [
                    "workloads"
                ],
                "summary": "Start a stopped workload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workload name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Workload not found",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Start failed",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workloads/{name}/stop": {
            "post": {
                "description": "Stops the containers for a workload without removing them",
                "tags": [
                    "workloads"
                ],
                "summary": "Stop a running workload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workload name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Workload not found",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Stop failed",
                        "schema": {
                            "$ref": "#/definitions/agent.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "agent.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "workload not found"
                }
            }
        },
        "agent.HealthResponse": {
            "type": "object",
            "properties": {
                "healthy": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "string",
                    "example": "abc123def456"
                },
                "mesh_ip": {
                    "type": "string",
                    "example": "10.100.42.1"
                },
                "name": {
                    "type": "string",
                    "example": "node1"
                },
                "public_ip": {
                    "type": "string",
                    "example": "203.0.113.1"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-02T15:04:05Z"
                },
                "warp_ip": {
                    "type": "string",
                    "example": "100.96.0.5"
                },
                "wireguard_mode": {
                    "type": "string",
                    "example": "kernel"
                },
                "workloads_local": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "nginx:10.100.50.1:running",
                        "redis:10.100.50.2:stopped"
                    ]
                },
                "workloads_total": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "agent.JoinRequest": {
            "type": "object",
            "properties": {
                "endpoint": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mesh_ip": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "public_key": {
                    "type": "string"
                },
                "secret": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "agent.JoinResponse": {
            "type": "object",
            "properties": {
                "cf_token": {
                    "type": "string"
                },
                "peers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/agent.Peer"
                    }
                },
                "workloads": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/agent.Workload"
                    }
                }
            }
        },
        "agent.MoveRequest": {
            "type": "object",
            "properties": {
                "to": {
                    "type": "string",
                    "example": "node2"
                }
            }
        },
        "agent.NodeInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "abc123def456"
                },
                "mesh_ip": {
                    "type": "string",
                    "example": "10.100.42.1"
                },
                "name": {
                    "type": "string",
                    "example": "node1"
                },
                "public_key": {
                    "type": "string",
                    "example": "..."
                },
                "warp_ip": {
                    "type": "string",
                    "example": "100.96.0.5"
                }
            }
        },
        "agent.Peer": {
            "type": "object",
            "properties": {
                "endpoint": {
                    "description": "public:wg_port",
                    "type": "string"
                },
                "healthy": {
                    "type": "boolean"
                },
                "id": {
                    "description": "HWID",
                    "type": "string"
                },
                "last_seen": {
                    "type": "string"
                },
                "mesh_ip": {
                    "type": "string"
                },
                "name": {
                    "description": "Hostname",
                    "type": "string"
                },
                "public_key": {
                    "type": "string"
                },
                "tunnel_host": {
                    "description": "Peer-specific tunnel hostname (e.g., \"node1.cluster.example.com\")",
                    "type": "string"
                },
                "warp_ip": {
                    "description": "Cloudflare WARP IP (CGNAT range, e.g., \"100.96.x.x\")",
                    "type": "string"
                }
            }
        },
        "agent.StatusResponse": {
            "type": "object",
            "properties": {
                "node": {
                    "$ref": "#/definitions/agent.NodeInfo"
                },
                "peers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/agent.Peer"
                    }
                },
                "tunnel": {
                    "$ref": "#/definitions/agent.TunnelStatus"
                },
                "warp": {
                    "$ref": "#/definitions/agent.WarpStatus"
                },
                "wireguard": {
                    "$ref": "#/definitions/agent.WireGuardStatus"
                },
                "workloads": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/agent.Workload"
                    }
                }
            }
        },
        "agent.TokenResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string",
                    "example": "2024-01-02T15:04:05Z"
                },
                "token": {
                    "type": "string",
                    "example": "abc123..."
                }
            }
        },
        "agent.TunnelRequest": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhIjoiNjA2..."
                }
            }
        },
        "agent.TunnelStatus": {
            "type": "object",
            "properties": {
                "configured": {
                    "type": "boolean",
                    "example": true
                },
                "running": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "agent.WarpStatus": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean",
                    "example": false
                },
                "ip": {
                    "type": "string",
                    "example": "100.96.0.5"
                }
            }
        },
        "agent.WireGuardStatus": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "mode": {
                    "description": "\"kernel\" or \"dummy\"",
                    "type": "string",
                    "example": "kernel"
                }
            }
        },
        "agent.Workload": {
            "type": "object",
            "properties": {
                "autostart": {
                    "description": "Auto-start when Jetty starts up",
                    "type": "boolean"
                },
                "compose": {
                    "type": "string"
                },
                "mesh_ip": {
                    "description": "Unique lock",
                    "type": "string"
                },
                "name": {
                    "description": "DNS hostname",
                    "type": "string"
                },
                "owner": {
                    "description": "Node HWID",
                    "type": "string"
                },
                "revive": {
                    "description": "Auto-failover to another node if owner dies",
                    "type": "boolean"
                },
                "version": {
                    "description": "Unix timestamp",
                    "type": "integer"
                }
            }
        },
        "agent.WorkloadRequest": {
            "type": "object",
            "properties": {
                "autostart": {
                    "type": "boolean",
                    "example": true
                },
                "compose": {
                    "type": "string",
                    "example": "version: '3'\nservices:\n  web:\n    image: nginx"
                },
                "mesh_ip": {
                    "type": "string",
                    "example": "10.100.50.1"
                },
                "name": {
                    "type": "string",
                    "example": "nginx"
                },
                "revive": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Jetty API",
	Description:      "P2P Docker Compose orchestration with WireGuard mesh networking",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
